### ISSUE TITLE
List of ESP32 devices that are 802.15.4-capable

### ISSUE THREAD

**Issue by drobertson123** [openthread/ot-esp32#13]
I can find no indication on the Espressif web site that ESP32 is 802.15.4 capable. Is there a resource somewhere that shows what chips will work and which will not?

I would love to use this library but I don't know if/where it will function.

**Comment by jwhui** [comment]
I'm not aware of any existing ESP32 devices that include IEEE 802.15.4. This repo currently requires an IEEE 802.15.4 SoC that implements the [Radio Co-Processor](https://openthread.io/platforms#radio-co-processor-rcp). OpenThread on the ESP32 will communicate with the RCP via UART.

Hope that helps.

**Comment by drobertson123** [comment]
Thank you. That clears up a significant point of confusion.

**Comment by wgtdkp** [comment]
> I would love to use this library but I don't know if/where it will function.

@drobertson123 you may start with the the [example](https://github.com/openthread/ot-esp32/tree/master/example) application.

**Comment by bylmzio** [comment]
What about
Espressif ESP32-WROOM-32D ?
is this capable of IEEE 802.15.4

**Comment by jwhui** [comment]
@bunower , the Espressif ESP32-WROOM-32D does not directly support IEEE 802.15.4.

**Comment by gabekassel** [comment]
https://www.espressif.com/en/news/ESP32_H2 🤞

**Comment by unitware** [comment]
@gabekassel that will do 802.15.4, but not WiFi :(

**Comment by jwhui** [comment]
> @gabekassel that will do 802.15.4, but not WiFi :(

@unitware, Espressif supports a multi-chip Wi-Fi + 802.15.4 solution. See the [OpenThread Border Router Guide](https://openthread.io/guides/border-router/espressif-esp32) for more details.

**Comment by unitware** [comment]
Yes, but I was looking forward to a single cpu solution and was misreading the press releases in the beginning 

Skickat från min iPhone

**Comment by jwhui** [comment]
Closing stale issue.
