### ISSUE TITLE
Which ESP32 should i get

### ISSUE THREAD

**Issue by tevzkadis** [openthread/ot-esp32#21]
Which ESP32 would be the best for using thread protocol through a radio co-processor design.

**Comment by jwhui** [comment]
> Which ESP32 would be the best for using thread protocol through a radio co-processor design.

You may find our [ESP Thread Border Router guide](https://openthread.io/guides/border-router/espressif-esp32) helpful.

**Comment by jwhui** [comment]
Closing stale issue.
