### ISSUE TITLE
[cli] scan command without thread configuration will crash the system

### ISSUE THREAD

**Issue by lanyuwen** [openthread/ot-esp32#6]
scan command without thread configuration will crash the system, no problem if using it after thread interface gets up.

**Comment by wgtdkp** [comment]
This is a bug in OpenThread `RadioSpinel` implementation. PR  https://github.com/openthread/openthread/pull/5068 is submitted, you may checkout it and test at your local.

I will later update the openthread submodule once the PR got merged.

**Comment by jwhui** [comment]
https://github.com/openthread/openthread/pull/5068 has been merged.

**Comment by wgtdkp** [comment]
> [openthread/openthread#5068](https://github.com/openthread/openthread/pull/5068) has been merged.

will fire a PR after testing on real device with latest openthread tomorrow.

**Comment by lanyuwen** [comment]
it won't crash anymore, however, still no output until thread interface is up.

**Comment by wgtdkp** [comment]
@lanyuwen 
> it won't crash anymore, however, still no output until thread interface is up.

the `scan` command scans for existing Thread Networks, is there already a Thread Network that is reachable from the ESP32 node?

**Comment by lanyuwen** [comment]
I can get some results after issuing "ifconfig up", or "ifconfig up" and "ifconfig down". However, I got nothing unless these commands executed.

I don't think this behavior is expected. But I think this is a low priority problem and can be tracked by a separated issue. Let's close this one for now.

**Comment by lanyuwen** [comment]
reopened to track the scan failure fix progress
